/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as SiteRouteImport } from './routes/_site'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as SiteIndexRouteImport } from './routes/_site.index'
import { Route as AppStandardsRouteImport } from './routes/app.standards'
import { Route as AppRunsRouteImport } from './routes/app.runs'
import { Route as AppFrictionRouteImport } from './routes/app.friction'
import { Route as AppConfigRouteImport } from './routes/app.config'
import { Route as AppPlansIndexRouteImport } from './routes/app.plans.index'
import { Route as SiteStandardsPacksIndexRouteImport } from './routes/_site.standards-packs.index'
import { Route as SiteCommandsIndexRouteImport } from './routes/_site.commands.index'
import { Route as AppRunsRunIdRouteImport } from './routes/app.runs_.$runId'
import { Route as AppPlansNameRouteImport } from './routes/app.plans.$name'
import { Route as SiteDocsDocRouteImport } from './routes/_site.docs.$doc'
import { Route as SiteCommandsCommandRouteImport } from './routes/_site.commands.$command'
import { Route as SiteStandardsPacksLibraryRulesRuleRouteImport } from './routes/_site.standards-packs.$library.rules.$rule'
import { Route as SiteStandardsPacksLibraryPacksPackRouteImport } from './routes/_site.standards-packs.$library.packs.$pack'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteRoute = SiteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRoute,
} as any)
const AppStandardsRoute = AppStandardsRouteImport.update({
  id: '/standards',
  path: '/standards',
  getParentRoute: () => AppRoute,
} as any)
const AppRunsRoute = AppRunsRouteImport.update({
  id: '/runs',
  path: '/runs',
  getParentRoute: () => AppRoute,
} as any)
const AppFrictionRoute = AppFrictionRouteImport.update({
  id: '/friction',
  path: '/friction',
  getParentRoute: () => AppRoute,
} as any)
const AppConfigRoute = AppConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => AppRoute,
} as any)
const AppPlansIndexRoute = AppPlansIndexRouteImport.update({
  id: '/plans/',
  path: '/plans/',
  getParentRoute: () => AppRoute,
} as any)
const SiteStandardsPacksIndexRoute = SiteStandardsPacksIndexRouteImport.update({
  id: '/standards-packs/',
  path: '/standards-packs/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteCommandsIndexRoute = SiteCommandsIndexRouteImport.update({
  id: '/commands/',
  path: '/commands/',
  getParentRoute: () => SiteRoute,
} as any)
const AppRunsRunIdRoute = AppRunsRunIdRouteImport.update({
  id: '/runs_/$runId',
  path: '/runs/$runId',
  getParentRoute: () => AppRoute,
} as any)
const AppPlansNameRoute = AppPlansNameRouteImport.update({
  id: '/plans/$name',
  path: '/plans/$name',
  getParentRoute: () => AppRoute,
} as any)
const SiteDocsDocRoute = SiteDocsDocRouteImport.update({
  id: '/docs/$doc',
  path: '/docs/$doc',
  getParentRoute: () => SiteRoute,
} as any)
const SiteCommandsCommandRoute = SiteCommandsCommandRouteImport.update({
  id: '/commands/$command',
  path: '/commands/$command',
  getParentRoute: () => SiteRoute,
} as any)
const SiteStandardsPacksLibraryRulesRuleRoute =
  SiteStandardsPacksLibraryRulesRuleRouteImport.update({
    id: '/standards-packs/$library/rules/$rule',
    path: '/standards-packs/$library/rules/$rule',
    getParentRoute: () => SiteRoute,
  } as any)
const SiteStandardsPacksLibraryPacksPackRoute =
  SiteStandardsPacksLibraryPacksPackRouteImport.update({
    id: '/standards-packs/$library/packs/$pack',
    path: '/standards-packs/$library/packs/$pack',
    getParentRoute: () => SiteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof SiteIndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/config': typeof AppConfigRoute
  '/app/friction': typeof AppFrictionRoute
  '/app/runs': typeof AppRunsRoute
  '/app/standards': typeof AppStandardsRoute
  '/app/': typeof AppIndexRoute
  '/commands/$command': typeof SiteCommandsCommandRoute
  '/docs/$doc': typeof SiteDocsDocRoute
  '/app/plans/$name': typeof AppPlansNameRoute
  '/app/runs/$runId': typeof AppRunsRunIdRoute
  '/commands/': typeof SiteCommandsIndexRoute
  '/standards-packs/': typeof SiteStandardsPacksIndexRoute
  '/app/plans/': typeof AppPlansIndexRoute
  '/standards-packs/$library/packs/$pack': typeof SiteStandardsPacksLibraryPacksPackRoute
  '/standards-packs/$library/rules/$rule': typeof SiteStandardsPacksLibraryRulesRuleRoute
}
export interface FileRoutesByTo {
  '/app/config': typeof AppConfigRoute
  '/app/friction': typeof AppFrictionRoute
  '/app/runs': typeof AppRunsRoute
  '/app/standards': typeof AppStandardsRoute
  '/': typeof SiteIndexRoute
  '/app': typeof AppIndexRoute
  '/commands/$command': typeof SiteCommandsCommandRoute
  '/docs/$doc': typeof SiteDocsDocRoute
  '/app/plans/$name': typeof AppPlansNameRoute
  '/app/runs/$runId': typeof AppRunsRunIdRoute
  '/commands': typeof SiteCommandsIndexRoute
  '/standards-packs': typeof SiteStandardsPacksIndexRoute
  '/app/plans': typeof AppPlansIndexRoute
  '/standards-packs/$library/packs/$pack': typeof SiteStandardsPacksLibraryPacksPackRoute
  '/standards-packs/$library/rules/$rule': typeof SiteStandardsPacksLibraryRulesRuleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_site': typeof SiteRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/app/config': typeof AppConfigRoute
  '/app/friction': typeof AppFrictionRoute
  '/app/runs': typeof AppRunsRoute
  '/app/standards': typeof AppStandardsRoute
  '/_site/': typeof SiteIndexRoute
  '/app/': typeof AppIndexRoute
  '/_site/commands/$command': typeof SiteCommandsCommandRoute
  '/_site/docs/$doc': typeof SiteDocsDocRoute
  '/app/plans/$name': typeof AppPlansNameRoute
  '/app/runs_/$runId': typeof AppRunsRunIdRoute
  '/_site/commands/': typeof SiteCommandsIndexRoute
  '/_site/standards-packs/': typeof SiteStandardsPacksIndexRoute
  '/app/plans/': typeof AppPlansIndexRoute
  '/_site/standards-packs/$library/packs/$pack': typeof SiteStandardsPacksLibraryPacksPackRoute
  '/_site/standards-packs/$library/rules/$rule': typeof SiteStandardsPacksLibraryRulesRuleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/config'
    | '/app/friction'
    | '/app/runs'
    | '/app/standards'
    | '/app/'
    | '/commands/$command'
    | '/docs/$doc'
    | '/app/plans/$name'
    | '/app/runs/$runId'
    | '/commands/'
    | '/standards-packs/'
    | '/app/plans/'
    | '/standards-packs/$library/packs/$pack'
    | '/standards-packs/$library/rules/$rule'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/app/config'
    | '/app/friction'
    | '/app/runs'
    | '/app/standards'
    | '/'
    | '/app'
    | '/commands/$command'
    | '/docs/$doc'
    | '/app/plans/$name'
    | '/app/runs/$runId'
    | '/commands'
    | '/standards-packs'
    | '/app/plans'
    | '/standards-packs/$library/packs/$pack'
    | '/standards-packs/$library/rules/$rule'
  id:
    | '__root__'
    | '/_site'
    | '/app'
    | '/app/config'
    | '/app/friction'
    | '/app/runs'
    | '/app/standards'
    | '/_site/'
    | '/app/'
    | '/_site/commands/$command'
    | '/_site/docs/$doc'
    | '/app/plans/$name'
    | '/app/runs_/$runId'
    | '/_site/commands/'
    | '/_site/standards-packs/'
    | '/app/plans/'
    | '/_site/standards-packs/$library/packs/$pack'
    | '/_site/standards-packs/$library/rules/$rule'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SiteRoute: typeof SiteRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/app/standards': {
      id: '/app/standards'
      path: '/standards'
      fullPath: '/app/standards'
      preLoaderRoute: typeof AppStandardsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/runs': {
      id: '/app/runs'
      path: '/runs'
      fullPath: '/app/runs'
      preLoaderRoute: typeof AppRunsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/friction': {
      id: '/app/friction'
      path: '/friction'
      fullPath: '/app/friction'
      preLoaderRoute: typeof AppFrictionRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/config': {
      id: '/app/config'
      path: '/config'
      fullPath: '/app/config'
      preLoaderRoute: typeof AppConfigRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/plans/': {
      id: '/app/plans/'
      path: '/plans'
      fullPath: '/app/plans/'
      preLoaderRoute: typeof AppPlansIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_site/standards-packs/': {
      id: '/_site/standards-packs/'
      path: '/standards-packs'
      fullPath: '/standards-packs/'
      preLoaderRoute: typeof SiteStandardsPacksIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/commands/': {
      id: '/_site/commands/'
      path: '/commands'
      fullPath: '/commands/'
      preLoaderRoute: typeof SiteCommandsIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/app/runs_/$runId': {
      id: '/app/runs_/$runId'
      path: '/runs/$runId'
      fullPath: '/app/runs/$runId'
      preLoaderRoute: typeof AppRunsRunIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/plans/$name': {
      id: '/app/plans/$name'
      path: '/plans/$name'
      fullPath: '/app/plans/$name'
      preLoaderRoute: typeof AppPlansNameRouteImport
      parentRoute: typeof AppRoute
    }
    '/_site/docs/$doc': {
      id: '/_site/docs/$doc'
      path: '/docs/$doc'
      fullPath: '/docs/$doc'
      preLoaderRoute: typeof SiteDocsDocRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/commands/$command': {
      id: '/_site/commands/$command'
      path: '/commands/$command'
      fullPath: '/commands/$command'
      preLoaderRoute: typeof SiteCommandsCommandRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/standards-packs/$library/rules/$rule': {
      id: '/_site/standards-packs/$library/rules/$rule'
      path: '/standards-packs/$library/rules/$rule'
      fullPath: '/standards-packs/$library/rules/$rule'
      preLoaderRoute: typeof SiteStandardsPacksLibraryRulesRuleRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/standards-packs/$library/packs/$pack': {
      id: '/_site/standards-packs/$library/packs/$pack'
      path: '/standards-packs/$library/packs/$pack'
      fullPath: '/standards-packs/$library/packs/$pack'
      preLoaderRoute: typeof SiteStandardsPacksLibraryPacksPackRouteImport
      parentRoute: typeof SiteRoute
    }
  }
}

interface SiteRouteChildren {
  SiteIndexRoute: typeof SiteIndexRoute
  SiteCommandsCommandRoute: typeof SiteCommandsCommandRoute
  SiteDocsDocRoute: typeof SiteDocsDocRoute
  SiteCommandsIndexRoute: typeof SiteCommandsIndexRoute
  SiteStandardsPacksIndexRoute: typeof SiteStandardsPacksIndexRoute
  SiteStandardsPacksLibraryPacksPackRoute: typeof SiteStandardsPacksLibraryPacksPackRoute
  SiteStandardsPacksLibraryRulesRuleRoute: typeof SiteStandardsPacksLibraryRulesRuleRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteIndexRoute: SiteIndexRoute,
  SiteCommandsCommandRoute: SiteCommandsCommandRoute,
  SiteDocsDocRoute: SiteDocsDocRoute,
  SiteCommandsIndexRoute: SiteCommandsIndexRoute,
  SiteStandardsPacksIndexRoute: SiteStandardsPacksIndexRoute,
  SiteStandardsPacksLibraryPacksPackRoute:
    SiteStandardsPacksLibraryPacksPackRoute,
  SiteStandardsPacksLibraryRulesRuleRoute:
    SiteStandardsPacksLibraryRulesRuleRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

interface AppRouteChildren {
  AppConfigRoute: typeof AppConfigRoute
  AppFrictionRoute: typeof AppFrictionRoute
  AppRunsRoute: typeof AppRunsRoute
  AppStandardsRoute: typeof AppStandardsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppPlansNameRoute: typeof AppPlansNameRoute
  AppRunsRunIdRoute: typeof AppRunsRunIdRoute
  AppPlansIndexRoute: typeof AppPlansIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppConfigRoute: AppConfigRoute,
  AppFrictionRoute: AppFrictionRoute,
  AppRunsRoute: AppRunsRoute,
  AppStandardsRoute: AppStandardsRoute,
  AppIndexRoute: AppIndexRoute,
  AppPlansNameRoute: AppPlansNameRoute,
  AppRunsRunIdRoute: AppRunsRunIdRoute,
  AppPlansIndexRoute: AppPlansIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SiteRoute: SiteRouteWithChildren,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
