export const StructuralCheck = {
	PathExists: 'path-exists',
	ProsePathExists: 'prose-path-exists',
	ScriptExists: 'script-exists',
	NoPlaceholders: 'no-placeholders',
	SectionsPresent: 'sections-present',
	ScopeWithinGuardrail: 'scope-within-guardrail',
	NamingMatches: 'naming-matches',
	PackagesIdentifiable: 'packages-identifiable',
	FileProvenance: 'file-provenance',
	HandoffChained: 'handoff-chained',
	DeclarationConsistent: 'declaration-consistent',
	CreatedFilesWithinCeiling: 'created-files-within-ceiling',
	TouchedFilesWithinCeiling: 'touched-files-within-ceiling',
	PhaseCount: 'phase-count',
	MoveWellFormed: 'move-well-formed',
	LedgerWellFormed: 'ledger-well-formed',
	LedgerCovers: 'ledger-covers',
	DecisionLogCurrent: 'decision-log-current',
	GlobalConstraintsCurrent: 'global-constraints-current',
	HandoffDeclared: 'handoff-declared',
	RenamesWellFormed: 'renames-well-formed',
} as const;

export type StructuralCheck = (typeof StructuralCheck)[keyof typeof StructuralCheck];
